blank_issues_enabled: true
contact_links:
  - name: Questions, help, and discussion
    url: https://reddit.com/r/yasbd_lib
    about: Ask questions, share projects, get help, or discuss anything yasbd-lib related
